const data = [
  {
    id: 0,
    profileImg: 'image.png',
    company: 'Fiverr',
    name: 'Adeel H.',
    level: 'Client',
    work: 'Custom Stripe Integration',
    date: '24 April, 2025',
    testimony: `Great experience working with Ahsaan. He understood everything clearly and delivered exactly what I needed. The payment flow works perfectly now. Will definitely hire again.`,
  },
  {
    id: 1,
    profileImg: 'image.png',
    company: 'Fiverr',
    name: 'Alina',
    level: 'Client',
    work: 'React Frontend Fixes',
    date: '11 April, 2025',
    testimony: `Very professional and fast. Ahsaan fixed all the UI issues on my React site and improved the responsiveness. Communication was smooth throughout.`,
  },
  {
    id: 2,
    profileImg: 'image.png',
    company: 'Fiverr',
    name: 'Jorje.',
    level: 'Client',
    work: 'Shopify Custom Features',
    date: '29 March, 2025',
    testimony: `He delivered clean and well‑structured code. The custom cart system and validations work flawlessly. Appreciate the effort!`,
  },
  {
    id: 3,
    profileImg: 'image.png',
    company: 'Fiverr',
    name: 'Helena R',
    level: 'Client',
    work: 'API Integration + Dashboard',
    date: '14 March, 2025',
    testimony: `Reliable and skilled developer. He integrated my APIs, fixed several bugs, and improved the dashboard speed. Very happy with the results.`,
  },
  {
    id: 4,
    profileImg: 'image.png',
    company: 'Fiverr',
    name: 'Kamran',
    level: 'Client',
    work: 'Website Debugging & Speed Optimization',
    date: '08 February, 2025',
    testimony: `Good work! My site was slow and had multiple issues. Ahsaan fixed all of them and improved the loading time noticeably. Recommended.`,
  },
];

export default data;
